version: '3'
services:
    dhcpsrv:
        build: .
        ports:
            - "67:67/udp"
        hostname: dhcpsrv.ctnr.com

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
